# Generated by Django 3.1.3 on 2020-12-02 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vessels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipament",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vessels.vessel",
                    ),
                ),
            ],
        ),
    ]
